# Generated by extendr: Do not edit by hand
# nolint start

#' Compute Gaussian regression sufficient statistics without calling the R API
#' from worker threads.
#'
#' @param x Column-major numeric design matrix.
#' @param y Numeric response vector.
#' @param n Number of rows.
#' @param p Number of columns.
#' @return Internal sufficient-statistics list.
#' @keywords internal
dsem_ar_sufficient <- function(x, y, n, p) .Call(wrap__dsem_ar_sufficient, x, y, n, p)

# nolint end
